# Generated by Django 3.2.16 on 2024-06-28 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registro',
            new_name='RegistroTemperatura',
        ),
    ]
